'use strict';
let D, F, E, S, C;
const state = {layer:'all',slot:'quarter',company:'all',sort:'revenue',bridge:'coreweave'};
const layers = {hardware:'硬件与制造',cloud:'云与算力',model:'模型',application:'企业应用',distribution:'分发与广告'};
const colors = {hardware:'#087f78',cloud:'#3869ac',model:'#7b58a3',application:'#ad7025',distribution:'#75685c'};
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,n=1)=>Number.isFinite(x)?x.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';
const bn=x=>fmt(x/1000,2);
const pct=x=>Number.isFinite(x)?`${fmt(x)}%`:'—';
const sign=x=>x>0?'+':'';
const ref=(ids,label='证据与计算 ↗')=>ids?.length?`<button class="ref" data-evidence="${esc([...new Set(ids)].join(','))}">${esc(label)}</button>`:'';
const metric=(id,text)=>id?`<button class="metric-link ${F[id]?.value<0?'negative':''}" data-evidence="${id}">${esc(text)}</button>`:`<span class="missing">—</span>`;
function head(n,title,en,ids=[]){return `<div class="section-head"><div><span class="eyebrow">${n} / ${en}</span><h2>${title}</h2></div>${ref(ids)}</div>`;}
function viewCard(v){return `<article class="view" style="--layer:${colors[v.id]}"><span class="tag opinion">分析判断 · ${layers[v.id]}</span><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p><p class="watch">继续观察：${esc(v.watch)}</p>${ref(v.fact_ids)}</article>`;}
function render(){
 const x=D.executive_view;
 $('#main').innerHTML=`
 <section id="overview"><div class="edition"><span class="eyebrow">FINRUNBOOK / SECTOR RESEARCH</span><span class="muted">2026.09.03 · ${D.sources.length} 项一手来源</span></div><h1>AI产业链：<br>增长、利润与资本回收</h1><p class="hero-summary"><strong>${esc(x.headline)}</strong><br>${esc(x.summary)}</p><div class="hero-meta"><span class="tag opinion">核心判断 · 非投资评级</span><span class="tag">${D.companies.length} 个财务比较对象</span><span class="tag">各自财年 + 最新季度</span>${ref([x.fact_ids[0]],'判断依据 ↗')}</div><div class="metrics">${x.decisive_metrics.map(m=>`<button class="metric" data-evidence="${m.fact_id}"><span class="label">${esc(m.label)}</span><span class="value">${m.unit==='%'?fmt(m.value):fmt(m.value,3)}<span class="unit">${m.unit==='%'?'%':'十亿美元'}</span></span><small>${esc(m.note)} ↗</small></button>`).join('')}</div><p class="panel-sub">以上为全报告固定摘要，不随下方公司筛选改变。金额单位：十亿美元（$bn）；除非另有说明，均为已披露实际值。</p></section>
 <section id="chain">${head('02','最终需求怎样转化为产业链收入','FLOW OF REVENUE')}<p class="intro">一笔终端支出可能先成为应用收入，再成为模型、云和芯片供应商的收入。沿途收入不能重复相加；融资也不能当作终端需求。</p><div class="chain">${[
 ['all','DEMAND','终端预算','企业、消费者、广告主'],['application','APPLICATION','应用 / 分发','工作流、订阅、广告'],['model','MODEL','基础模型','API、训练与任务服务'],['cloud','CLOUD','云与算力','GPU集群、通用云、自研芯片'],['hardware','HARDWARE','硬件 / 制造','加速器、网络、内存、晶圆']
 ].map(([l,en,t,n])=>`<button class="chain-node" data-chain="${l}" style="--layer:${colors[l]||'#75685c'}"><small>${en}</small><strong>${t}</strong><span>${n}</span></button>`).join('')}</div><div class="flow-detail"><div><strong>箭头表示付款与供给关系，不表示已测量的资金规模。</strong><p>模型公司也直接经营应用，云平台也提供模型和芯片；图示用于理解价值链，不假设企业只属于一层。</p></div>${ref(D.flows.flatMap(f=>f.fact_ids),'关系依据 ↗')}</div><div class="flow-list">${D.flows.map(f=>`<div class="flow-row"><strong>${esc(f.from)} ${f.kind==='financing'?'⇢':'→'} ${esc(f.to)}</strong> · ${esc(f.label)}<small>${esc(f.note)}</small>${ref(f.fact_ids)}</div>`).join('')}</div></section>
 <section id="comparison">${head('03','收入增长，是否变成了经营利润？','OPERATING ECONOMICS')}<p class="intro">看同一公司的同比变化，再横向判断经济性。AWS、Google Cloud采用分部口径，其余采用公司整体；这是一张经营比较表，不是AI市场份额表。</p><div class="controls"><div class="control"><label for="period">财务期间</label><select id="period"><option value="quarter">最新已披露季度</option><option value="annual">最近完整财年</option><option value="previous">前一完整财年</option></select></div><div class="control"><label for="layer">产业层级</label><select id="layer"><option value="all">全部财务样本</option>${Object.entries(layers).filter(([k])=>k!=='model').map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="control"><label for="company">公司 / 分部</label><select id="company"></select></div><div class="control"><label for="sort">排序（从高到低）</label><select id="sort"><option value="revenue">收入</option><option value="growth">收入同比</option><option value="op_margin">经营利润率</option></select></div><button id="reset-filters" class="ref">重置筛选</button></div><div id="filter-summary" class="filter-summary" aria-live="polite"></div><div id="comparison-body"></div><div class="notice">各公司季度截止日不同，具体日期见表内。公司整体、分部及TIFRS口径并列仅供参考；GAAP经营利润与调整后EBITDA不混用。未披露 / 未采集的可比基数显示“—”，不视为零。</div><div id="kpis" class="kpis"></div><div class="views">${D.sections.filter(v=>v.id!=='model').map(viewCard).join('')}</div></section>
 <section id="models">${head('04','模型竞争：财务规模之外，还有部署与分发','MODEL LANDSCAPE')}<p class="intro">模型公司正同时争取算力供给、开发者调用和终端用户。私营公司的经营披露并不完整，以下保留每项指标的定义与时点，不据此计算收入份额或利润排名。</p><div class="models-grid">${D.models.map(m=>`<article class="model-card"><h3>${esc(m.name)}</h3><div class="position">${esc(m.position)}</div><p style="font-size:14px">${esc(m.headline)}</p>${m.metrics.map(k=>`<div class="model-metric"><span>${esc(k.label)}</span><button data-evidence="${k.fact_id}">${esc(k.display)} ↗</button></div>`).join('')}<p class="model-boundary">${esc(m.boundary)}</p>${ref(m.fact_ids)}</article>`).join('')}</div><div class="views">${D.sections.filter(v=>v.id==='model').map(viewCard).join('')}</div></section>
 <section id="cash">${head('05','云的经营利润，不等于可以自由使用的现金','CAPITAL & CASH',D.cash.flatMap(c=>c.fact_ids))}<p class="intro">下面统一比较2026年4—6月的集团经营现金流与现金资本开支。这里衡量内部现金对设备投入的覆盖程度，不把全部资本开支称为AI投资，也不将季度现金缺口等同于偿债危机。</p><div class="legend"><span style="--c:#087f78">经营现金流 CFO</span><span style="--c:#c7a36a">现金资本开支</span><span>共用尺度 · 十亿美元</span></div><div class="cash-grid" style="margin-top:17px">${D.cash.map(c=>`<article class="cash-card"><h3>${esc(c.company)}</h3>${['cfo','capex'].map(k=>`<div class="cash-measure"><div class="cash-label"><span>${k==='cfo'?'经营现金流':'现金资本开支'}</span><button data-evidence="${c.metric_fact_ids[k]}">${bn(c[k])} ↗</button></div><div class="track"><div class="fill ${k}" style="width:${c[k]/60000*100}%"></div></div></div>`).join('')}<div class="cash-left"><span>CFO − 现金资本开支</span><button class="${c.cash_left<0?'negative':''}" data-evidence="${c.metric_fact_ids.cash_left}">${sign(c.cash_left)}${bn(c.cash_left)}</button></div><small>资本开支 / CFO：${metric(c.metric_fact_ids.coverage,pct(c.coverage))}<br>集团口径 · 非AI独立现金流</small></article>`).join('')}</div><div class="cash-bottom"><div class="notice">Meta：主图差额为 <strong>${bn(D.cash.find(c=>c.company==='Meta').cash_left)}</strong>；另扣融资租赁本金 <strong>${bn(D.cash.find(c=>c.company==='Meta').lease_principal)}</strong> 后，公司定义的自由现金流为 <strong>${bn(D.cash.find(c=>c.company==='Meta').official_fcf)}</strong> 十亿美元。${ref(D.cash.find(c=>c.company==='Meta').fact_ids)}</div><div class="notice">CoreWeave另列 <strong>${D.coreweave_cash.period}</strong>，不放进季度图：CFO <strong>${bn(D.coreweave_cash.cfo)}</strong>，资本开支 <strong>${bn(D.coreweave_cash.capex)}</strong>，差额 <strong>${bn(D.coreweave_cash.cash_left)}</strong> 十亿美元。${ref(D.coreweave_cash.fact_ids)}</div></div></section>
 <section id="bridges">${head('06','把增长与利润变化拆开解释','FINANCIAL BRIDGES')}<p class="intro">三个例子分别回答：利润指标漏掉了什么、增长有多少来自并购，以及成本上升由哪些因素驱动。</p><div class="tabs" role="group" aria-label="财务桥接选择"><button data-bridge="coreweave" class="active">CoreWeave · 利润调节</button><button data-bridge="salesforce">Salesforce · 并购贡献</button><button data-bridge="servicenow">ServiceNow · 成本拆解</button></div><div id="bridge-panel" class="panel" aria-live="polite"></div></section>
 <section id="outlook">${head('07','未来要验证的是经济性，而不只是需求','SCENARIOS & MONITORING')}<p class="intro">以下为分析情景，不分配主观概率，也不是管理层指引。重点是哪些数据会支持或推翻判断。</p><div class="outlook-grid">${D.outlook.map((o,i)=>`<article class="outlook-card"><span class="eyebrow">情景 0${i+1} · 非预测</span><h3>${esc(o.name)}</h3><p>${esc(o.mechanism)}</p><dl><dt>支持信号</dt><dd>${esc(o.confirm)}</dd><dt>反证信号</dt><dd>${esc(o.invalidate)}</dd></dl>${ref(o.fact_ids,'背景依据 ↗')}</article>`).join('')}</div><div class="scenario"><span class="tag opinion">交互算例 · 全部输入为假设</span><h3 style="margin-top:12px">${esc(D.scenario_model.title)}</h3><div class="scenario-grid"><div>${[['volume','付费任务量变化',-50,300],['price','每项任务收费变化',-80,100],['tokens','每项任务Token用量变化',-50,200],['cost','每Token成本变化',-90,100]].map(([k,l,min,max])=>`<div class="slider-row"><label for="scenario-${k}">${l}<output id="out-${k}" for="scenario-${k}"></output></label><input id="scenario-${k}" type="range" min="${min}" max="${max}" step="5" value="${D.scenario_model.defaults[k]}"></div>`).join('')}<button id="scenario-reset" class="ref">恢复演示假设</button></div><div id="scenario-results" class="scenario-results" aria-live="polite"></div></div><div class="notice">${esc(D.scenario_model.limitations)}</div></div></section>
 <section id="methodology">${head('08','可复核，也有明确边界','METHOD & EVIDENCE')}<div class="methods">${D.methodology.map((m,i)=>`<details ${i<2?'open':''}><summary>${esc(m.title)}</summary><p>${esc(m.text)}</p>${ref(m.fact_ids)}</details>`).join('')}</div><div class="provenance-footer"><div>${D.sources.length} 项一手来源 · ${D.facts.length} 条事实/计算/判断记录 · ${D.calculations.length} 项公式<br>FinRunbook → sector-overview → 分部分析 → 中文语气审校 → validator<br><span id="validation-footer"></span><br>由同一研究代理复核，不构成独立审计或准确率保证。</div><div class="footer-actions"><button id="all-sources" class="ref">浏览全部来源 ↗</button><a href="report-data.json" download>下载数据 JSON ↓</a></div></div></section>`;
 bind();updateComparison();renderBridge();renderScenario();renderValidation();
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.rail nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`));}})},{rootMargin:'-15% 0px -70% 0px'});
 document.querySelectorAll('main section').forEach(s=>observer.observe(s));
 let scheduled=false;
 window.addEventListener('scroll',()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{const parts=[...document.querySelectorAll('main section')];const current=parts.filter(s=>s.getBoundingClientRect().top<=155).pop()||parts[0];document.querySelectorAll('.rail nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${current.id}`));scheduled=false;});},{passive:true});
}
function bind(){
 for(const k of ['period','layer','company','sort'])$('#'+k).addEventListener('change',e=>{state[k==='period'?'slot':k]=e.target.value;if(k==='layer')state.company='all';updateComparison();});
 $('#reset-filters').onclick=()=>{Object.assign(state,{layer:'all',slot:'quarter',company:'all',sort:'revenue'});updateComparison();};
 $('#source-open').onclick=allSources;$('#all-sources').onclick=allSources;$('#dialog-close').onclick=()=>$('#evidence-dialog').close();$('#print').onclick=()=>window.print();
 $('#evidence-dialog').addEventListener('click',e=>{if(e.target===$('#evidence-dialog') && e.offsetX<0)$('#evidence-dialog').close();});
 document.addEventListener('click',e=>{
  const refButton=e.target.closest('[data-evidence]');if(refButton){showEvidence(refButton.dataset.evidence.split(','));return;}
  const company=e.target.closest('[data-company]');if(company){state.company=company.dataset.company;updateComparison();return;}
  const chain=e.target.closest('[data-chain]');if(chain){const l=chain.dataset.chain;if(l==='model')$('#models').scrollIntoView();else{state.layer=l;state.company='all';updateComparison();$('#comparison').scrollIntoView();}return;}
  const bridge=e.target.closest('[data-bridge]');if(bridge){state.bridge=bridge.dataset.bridge;renderBridge();}
 });
 document.addEventListener('keydown',e=>{const dot=e.target.closest('.dot');if(dot&&(e.key==='Enter'||e.key===' ')){e.preventDefault();state.company=dot.dataset.company;updateComparison();}});
 document.querySelectorAll('input[type=range]').forEach(i=>i.addEventListener('input',renderScenario));
 $('#scenario-reset').onclick=()=>{for(const k of ['volume','price','tokens','cost'])$('#scenario-'+k).value=D.scenario_model.defaults[k];renderScenario();};
}
function updateComparison(){
 const choices=D.companies.filter(c=>state.layer==='all'||c.layer===state.layer);
 $('#company').innerHTML='<option value="all">当前层级全部公司</option>'+choices.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 if(!choices.some(c=>c.id===state.company))state.company='all';
 $('#company').value=state.company;$('#layer').value=state.layer;$('#period').value=state.slot;$('#sort').value=state.sort;
 const rows=D.observations.filter(o=>o.slot===state.slot&&choices.some(c=>c.id===o.company)&&(state.company==='all'||o.company===state.company)).sort((a,b)=>(b.values[state.sort]??-Infinity)-(a.values[state.sort]??-Infinity));
 const featured=rows[0],c=D.companies.find(c=>c.id===featured.company);
 const periodLabel={quarter:'最新已披露季度',annual:'最近完整财年',previous:'前一完整财年'}[state.slot];
 $('#filter-summary').textContent=`当前：${periodLabel} · ${layers[state.layer]||'全部层级'} · ${rows.length} 个比较对象 · 收入以十亿美元列示。年度曲线固定展示所选对象的完整财年。`;
 $('#comparison-body').innerHTML=`<div class="compare-layout"><div class="panel"><h3>增长 × 经营利润率</h3><p class="panel-sub">每个点等大，不代表份额或市值。点击公司聚焦；悬停查看准确期间与数值。</p>${scatter(rows)}<div class="legend">${Object.entries(colors).filter(([k])=>k!=='model').map(([k,v])=>`<span style="--c:${v}">${layers[k]}</span>`).join('')}</div></div><div class="panel company-note"><div><span class="eyebrow">当前首位 / ${esc(layers[c.layer])}</span><h4>${esc(c.name)}</h4><p class="basis">${esc(c.basis)}<br>${esc(featured.period)} · 截至 ${esc(featured.period_end)}</p><div class="m-label">变现方式 · 分析归纳</div><p>${esc(c.mechanism)}</p></div><div><div class="m-label">判断边界</div><p class="risk">${esc(c.risk)}</p>${ref(c.fact_ids,'公司口径与依据 ↗')}</div></div></div><div class="table-wrap"><table id="financial-table"><thead><tr><th>公司 / 分部</th><th>实际期间 / 截止日</th><th class="numeric">收入 $bn</th><th class="numeric">收入同比</th><th class="numeric">经营利润 $bn</th><th class="numeric">经营利润率</th><th class="numeric">利润率变化 pp</th></tr></thead><tbody>${rows.map(o=>{const c=D.companies.find(c=>c.id===o.company),m=o.metric_fact_ids,v=o.values;return `<tr data-row-company="${c.id}"><td><button class="table-company" data-company="${c.id}">${esc(c.name)}</button><small style="display:block;font-size:10px">${c.id==='AWS'||c.id==='GCLOUD'?'分部':'公司整体'} · ${layers[c.layer]}</small></td><td class="period-cell">${esc(o.period)}<small>${esc(o.period_end)}</small></td><td class="numeric">${metric(m.revenue,bn(v.revenue))}</td><td class="numeric">${metric(m.growth,pct(v.growth))}</td><td class="numeric">${metric(m.op_income,bn(v.op_income))}</td><td class="numeric">${metric(m.op_margin,pct(v.op_margin))}</td><td class="numeric">${metric(m.margin_change,sign(v.margin_change)+fmt(v.margin_change))}</td></tr>`;}).join('')}</tbody></table></div><div class="panel trend-layout"><div><div class="panel-top"><h3>${esc(c.name)} · 完整财年收入轨迹</h3>${ref(D.observations.filter(o=>o.company===c.id&&o.slot!=='quarter').flatMap(o=>[o.metric_fact_ids.revenue]),'年度依据 ↗')}</div><p class="panel-sub">美元收入，十亿美元 · 不把最新季度年化后加入曲线</p>${trend(c.id)}</div><div>${historyNumbers(c.id)}<p class="panel-sub" style="margin-top:16px">各公司财政年度不同。横向图反映当前所选期间，曲线只展示同一公司连续完整年度；没有把两者连接成一条时间序列。</p></div></div>`;
 const kpis=D.kpis.filter(k=>choices.some(c=>c.id===k.company)&&(state.company==='all'||k.company===state.company));
 $('#kpis').innerHTML=kpis.length?`<div style="grid-column:1/-1;font-size:12px;color:var(--muted);margin-top:8px">产品补充指标 · 固定为各自最新披露时点，不随财年筛选变化；以下指标不能相加。</div>`+kpis.map(k=>{const f=F[k.fact_ids[0]],pre=f.comparator||'';let value=k.units==='percent'?pct(k.value):k.units==='million seats'?`${fmt(k.value,0)} 百万席位`:`$${bn(k.value)}bn`;return `<button class="kpi" data-evidence="${k.fact_ids[0]}"><span class="company">${esc(D.companies.find(c=>c.id===k.company).name)} · ${esc(k.period)}</span><br>${esc(k.label)}<strong>${esc(pre)} ${value} ↗</strong><small>${esc(k.note)}</small></button>`;}).join(''):'';
}
function scatter(rows){
 const data=rows.filter(o=>Number.isFinite(o.values.growth)&&Number.isFinite(o.values.op_margin));
 if(!data.length)return '<p class="notice">该选择没有足够的可比同比数据；请查看财务表中的实际值。</p>';
 const W=580,H=310,p={l:48,r:28,t:25,b:44};
 const xmin=Math.min(0,Math.floor(Math.min(...data.map(o=>o.values.growth))/25)*25),xmax=Math.max(50,Math.ceil(Math.max(...data.map(o=>o.values.growth))/50)*50);
 const ymin=Math.min(-10,Math.floor(Math.min(...data.map(o=>o.values.op_margin))/10)*10),ymax=Math.max(50,Math.ceil(Math.max(...data.map(o=>o.values.op_margin))/10)*10);
 const x=v=>p.l+(v-xmin)/(xmax-xmin)*(W-p.l-p.r),y=v=>H-p.b-(v-ymin)/(ymax-ymin)*(H-p.t-p.b);
 let svg=`<svg class="scatter" viewBox="0 0 ${W} ${H}" role="img" aria-label="收入同比与经营利润率散点图"><text x="${p.l}" y="12">经营利润率 %</text>`;
 for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4;svg+=`<line x1="${p.l}" x2="${W-p.r}" y1="${y(v)}" y2="${y(v)}" stroke="#e5eae5"/><text x="${p.l-8}" y="${y(v)+3}" text-anchor="end">${fmt(v,0)}</text>`;const xx=xmin+(xmax-xmin)*i/4;svg+=`<text x="${x(xx)}" y="${H-p.b+18}" text-anchor="middle">${fmt(xx,0)}</text>`;}
 svg+=`<line x1="${p.l}" x2="${W-p.r}" y1="${y(0)}" y2="${y(0)}" stroke="#bccbc3" stroke-dasharray="4 4"/><text x="${W-p.r}" y="${H-3}" text-anchor="end">收入同比 %</text>`;
 const placed=[];
 for(const o of data){const c=D.companies.find(c=>c.id===o.company),cx=x(o.values.growth),cy=y(o.values.op_margin);let ly=cy-10;for(let n=0;n<8&&placed.some(a=>Math.abs(a.x-cx)<58&&Math.abs(a.y-ly)<13);n++)ly+=14;ly=Math.max(20,Math.min(H-p.b-8,ly));placed.push({x:cx,y:ly});const anchor=cx>W-110?'end':'start',lx=cx+(anchor==='end'?-8:8);const label=`${c.name}: ${o.period}, ${o.period_end}; 收入同比${pct(o.values.growth)}; 经营利润率${pct(o.values.op_margin)}`;svg+=`<g class="dot" tabindex="0" role="button" data-company="${c.id}" aria-label="${esc(label)}"><title>${esc(label)}</title><circle cx="${cx}" cy="${cy}" r="5.5" fill="${colors[c.layer]}" stroke="white" stroke-width="1.5"/><text x="${lx}" y="${ly}" text-anchor="${anchor}">${esc(c.name)}</text></g>`;}
 return svg+'</svg>';
}
function annual(cid){return D.observations.filter(o=>o.company===cid&&o.slot!=='quarter').sort((a,b)=>a.period_end.localeCompare(b.period_end));}
function trend(cid){const a=annual(cid),W=470,H=205,max=Math.max(...a.map(o=>o.values.revenue))*1.12;const xx=i=>45+i*(W-90)/(a.length-1),yy=v=>H-43-v/max*(H-65);return `<svg class="trend" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(cid)}完整年度收入"><line x1="35" y1="${H-43}" x2="${W-25}" y2="${H-43}" stroke="#d8e1d8"/><polyline points="${a.map((o,i)=>`${xx(i)},${yy(o.values.revenue)}`).join(' ')}" fill="none" stroke="#087f78" stroke-width="2.5"/>${a.map((o,i)=>`<circle cx="${xx(i)}" cy="${yy(o.values.revenue)}" r="5" fill="#087f78"/><text x="${xx(i)}" y="${yy(o.values.revenue)-13}" text-anchor="middle">$${bn(o.values.revenue)}bn</text><text x="${xx(i)}" y="${H-21}" text-anchor="middle">${esc(o.period)}</text><text x="${xx(i)}" y="${H-5}" text-anchor="middle">${esc(o.period_end)}</text>`).join('')}</svg>`;}
function historyNumbers(cid){return `<div class="history-values">${annual(cid).map(o=>`<div>${esc(o.period)}<strong>${metric(o.metric_fact_ids.revenue,bn(o.values.revenue))}</strong><small>收入 · $bn</small><small>经营利润率 ${metric(o.metric_fact_ids.op_margin,pct(o.values.op_margin))}</small><small>收入同比 ${metric(o.metric_fact_ids.growth,pct(o.values.growth))}</small></div>`).join('')}</div>`;}
function renderBridge(){
 document.querySelectorAll('[data-bridge]').forEach(b=>{b.classList.toggle('active',b.dataset.bridge===state.bridge);b.setAttribute('aria-pressed',String(b.dataset.bridge===state.bridge));});
 const b=D.bridges[state.bridge],isNow=state.bridge==='servicenow';let rows=[];
 if(!isNow)rows.push({label:state.bridge==='coreweave'?'调整后EBITDA':'上年同期收入',value:b.start,kind:'neutral'});
 rows.push(...b.items);
 const max=Math.max(...rows.map(r=>Math.abs(r.value))),total=isNow?b.total:b.end;
 const title=isNow?'订阅成本总增加':state.bridge==='coreweave'?'GAAP净利润':'本期收入';
 $('#bridge-panel').innerHTML=`<div class="bridge-main"><div><h3>${esc(b.title)}</h3><p class="panel-sub">单位：百万美元 · ${esc(b.period)} · 各条为绝对金额或调节项，不是现金流</p>${rows.map(r=>`<div class="bridge-row"><span>${esc(r.label)}</span><div><div class="bridge-bar ${r.kind||((r.value<0)?'loss':'')}" style="width:${Math.max(Math.abs(r.value)/max*100,1)}%"></div></div><span class="bridge-amount ${r.value<0?'negative':''}">${r.kind?'':sign(r.value)}${fmt(r.value,0)}</span></div>`).join('')}<div class="bridge-total"><span>${title}</span><strong class="${total<0?'negative':''}">${fmt(total,0)}</strong></div></div><div class="bridge-copy"><span class="tag opinion">解释边界</span><p class="period">${esc(b.period)}</p><p>${esc(b.note)}</p>${state.bridge==='salesforce'?`<p>总增量 ${fmt(b.end-b.start,0)}，扣除Informatica贡献后的残差 ${fmt(b.items[1].value,0)}。残差 / 上年收入为 <strong>${pct(b.proxy)}</strong>，仅作增长代理。</p>`:''}${state.bridge==='coreweave'?'<p>经营利润、净利润与现金流是三种不同指标。资本开支不在此桥内扣除；现金投入另见上一节。</p>':''}${ref(b.fact_ids,'查看调节与原始来源 ↗')}</div></div>`;
}
function scenarioValues(a){const revenue=100*(1+a.volume/100)*(1+a.price/100),cost=40*(1+a.volume/100)*(1+a.tokens/100)*(1+a.cost/100);return {revenue,cost,contribution:revenue-cost};}
function renderScenario(){
 const a={};
 for(const k of ['volume','price','tokens','cost']){a[k]=Number($('#scenario-'+k).value);$('#out-'+k).textContent=sign(a[k])+a[k]+'%';}
 const v=scenarioValues(a);
 $('#scenario-results').innerHTML=`<span class="eyebrow">相对基准 · 基准收入 = 100</span><div class="scenario-value"><span>收入指数</span><strong id="scenario-revenue">${fmt(v.revenue)}</strong></div><div class="scenario-value"><span>推理变动成本</span><strong id="result-cost">${fmt(v.cost)}</strong></div><div class="scenario-value"><span>扣推理变动成本后贡献</span><strong id="scenario-contribution" class="${v.contribution<0?'negative':''}">${fmt(v.contribution)}</strong></div><p class="scenario-explain">基准贡献为60；当前变为${fmt(v.contribution)}，变化${sign(v.contribution-60)}${fmt(v.contribution-60)}。${v.contribution>60?'这组假设下，用量与成本变化足以抵消降价。':'这组假设下，用量增长未提高这一口径的贡献。'}这不是经营利润或净利润。</p><details><summary style="font-size:11px;cursor:pointer">展开计算公式</summary><div class="formula">收入 = 100 × ${fmt(1+a.volume/100,2)} × ${fmt(1+a.price/100,2)}<br>成本 = 40 × ${fmt(1+a.volume/100,2)} × ${fmt(1+a.tokens/100,2)} × ${fmt(1+a.cost/100,2)}<br>贡献 = 收入 − 推理变动成本</div></details>`;
}
function sourceCard(s){return `<article class="source-card" data-source="${s.id}"><span class="id">${s.id} · ${s.primary?'一手来源':'二手来源'}</span><h3>${esc(s.title)}</h3><p>${esc(s.publisher)} · ${esc(s.published_at||s.as_of_date||'日期未披露')}</p><p class="muted">采集时间：${esc(s.retrieved_at)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">打开原始文件 ↗</a></article>`;}
function openDialog(title,html){$('#evidence-title').textContent=title;$('#evidence-content').innerHTML=html;const d=$('#evidence-dialog');if(!d.open)d.showModal();d.scrollTop=0;}
function allSources(){openDialog('全部来源',`<p class="muted" style="font-size:12px">共${D.sources.length}项。SEC财报、公司业绩公告及模型厂商一手披露；私营厂商披露不等同于审计报表。</p><label for="source-search" class="eyebrow">搜索公司、文件或来源编号</label><input id="source-search" class="source-search" placeholder="例如 NVIDIA、10-K、OpenAI"><div id="source-count" class="panel-sub"></div><div class="source-list" id="source-list"></div>`);const draw=()=>{const q=$('#source-search').value.toLowerCase();const list=D.sources.filter(s=>[s.title,s.publisher,s.key,s.id].join(' ').toLowerCase().includes(q));$('#source-list').innerHTML=list.map(sourceCard).join('');$('#source-count').textContent=`${list.length} / ${D.sources.length} 项来源`;};$('#source-search').addEventListener('input',draw);draw();}
const statusNames={'company-reported':'公司披露','verified':'已复核','calculated':'计算结果','inferred':'分析推断','insufficient-evidence':'证据不足','conflicting':'存在冲突'};
function showEvidence(ids){
 const facts=[...new Set(ids)].map(id=>F[id]).filter(Boolean),srcs=[...new Set(facts.flatMap(f=>f.source_ids||[]))];
 const html=facts.map(f=>{const c=C[f.calculation_id];return `<article class="fact-card"><span class="id">${f.id} · ${statusNames[f.status]||esc(f.status)}</span><h3>${esc(f.statement)}</h3>${f.value!==undefined?`<div class="fact-value">${esc(f.comparator||'')}${fmt(f.value,Math.abs(f.value)<100?3:2)} <small>${esc(f.units)}</small></div>`:''}<p class="fact-meta">期间：${esc(f.period)}<br>币种：${esc(f.currency)}${f.basis?'<br>口径：'+esc(f.basis):''}</p>${f.reasoning?`<p><strong>判断过程：</strong>${esc(f.reasoning)}</p>`:''}${c?`<div class="formula">${c.id} · ${esc(c.description)}<br>公式：${esc(c.expression)}<br>${c.input_fact_ids.map((id,i)=>`x[${i}] = <button data-evidence="${id}">${id}</button> = ${fmt(F[id].value,3)}`).join('<br>')}<br>结果：${fmt(c.result,5)} ${esc(c.units)}</div>`:''}${f.supporting_fact_ids?.length?ref(f.supporting_fact_ids,'展开判断所依据的数据 ↗'):''}<details><summary>查看来源定位与摘录 / 转述</summary>${[...new Set(f.evidence_ids||[])].map(id=>{const e=E[id],s=S[e.source_id];return `<div class="evidence-quote"><strong>${e.id} · ${e.source_id}</strong><br>${esc(e.locator)}<br><br>${esc(e.content)}<br><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.publisher)} 原始文件 ↗</a></div>`;}).join('')}</details></article>`;}).join('');
 openDialog(facts.length===1?'数值、口径与计算':'判断与支撑数据',`<p class="muted" style="font-size:12px">${facts.length}条记录 · ${srcs.length}项来源。英文原始行与中文转述均保留来源定位；计算结果由输入事实重算。</p>${html}<div class="evidence-section-label">相关来源</div>${srcs.map(id=>sourceCard(S[id])).join('')}`);
}
function renderValidation(){const s=D.validation.status;const text=s==='PASS'?'结构与计算检查通过':s==='PASS_WITH_WARNINGS'?'校验完成 · 含披露限制':'校验未完成';$('#validation-rail').textContent=text;$('#validation-footer').textContent=text+'；具体边界见上方方法。';}
fetch('report-data.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(data=>{D=data;F=Object.fromEntries(D.facts.map(x=>[x.id,x]));E=Object.fromEntries(D.evidence.map(x=>[x.id,x]));S=Object.fromEntries(D.sources.map(x=>[x.id,x]));C=Object.fromEntries(D.calculations.map(x=>[x.id,x]));render();}).catch(e=>{$('#main').innerHTML=`<div class="error"><h2>报告数据未能读取</h2><p>${esc(e.message)}</p><p>请通过本地HTTP地址访问，并确保 report-data.json 与页面在同一目录。</p></div>`;console.error(e);});
