'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('report/report-data.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json();}).then(d=>{
 const F=Object.fromEntries(d.facts.map(f=>[f.id,f])),S=Object.fromEntries(d.sources.map(s=>[s.id,s])),E=Object.fromEntries(d.evidence.map(e=>[e.id,e]));
 const q=d.interim[3],china=d.regions.find(r=>r.period==='Q2 FY2026'&&r.region==='China Mainland'),on=d.peers.find(p=>p.name==='On');
 const cases=[
  {assumption:'International growth can offset weakness in the Americas.',status:'Challenged in the latest quarter',ids:[china.growth_cc,china.comp_cc,d.notes.conversion],metrics:[china.growth_cc,china.comp_cc],text:'The latest China revenue and comparable-sales observations challenge this illustrative assumption. The report also describes lower conversion despite higher traffic. This does not establish a permanent trend or a single cause.',next:'Watch comparable growth and conversion by region, keeping store expansion and currency effects separate.'},
  {assumption:'Improved inventory discipline means the earnings recovery has started.',status:'Mixed evidence',ids:[q.inventory_units,q.ex_refund_oi_growth,d.notes.cash,d.notes.inventory],metrics:[q.inventory_units,q.ex_refund_oi_growth],text:'Lower inventory units are consistent with tighter inventory control. Operating income still declines when the current-quarter tariff refund is excluded. Inventory improvement alone does not establish demand or earnings recovery.',next:'Look for sustained full-price selling and refund-excluded margin improvement. Check whether cash-flow gains persist after working-capital timing changes.'},
  {assumption:'Competitor growth proves that Lululemon customers are switching brands.',status:'Not established by the available evidence',ids:[on.metrics['CC growth'],d.notes.on,d.notes.athleta,d.diagnoses[2].fact_id],metrics:[on.metrics['CC growth']],text:'On’s growth is a relevant competitive signal, but its footwear-heavy mix and different geography and channels complicate comparison. The collected evidence does not trace the same customers from Lululemon to a named rival.',next:'A matched customer purchase panel or other direct switching evidence would be needed. Keep the destination and size of any share transfer unresolved.'}
 ];
 function evidence(id){const f=F[id];return `<div class="source" data-fact="${id}"><strong>${esc(f.statement)}</strong><br><small>${esc(id)} · ${esc(f.period||'See supporting disclosures')} · ${esc(f.status)}</small>${f.value!==undefined?`<p>Recorded value: ${esc(f.value)} ${esc(f.units)}${f.calculation_id?' · '+esc(f.calculation_id):''}</p>`:''}<p>${f.source_ids.map(s=>`<a target="_blank" rel="noopener" href="${esc(S[s].url)}">${esc(S[s].title)}</a>`).join('<br>')}</p><small>Source locators: ${f.evidence_ids.map(e=>esc(E[e].source_id+' '+E[e].locator)).join('; ')}</small></div>`;}
 document.querySelector('#checks').innerHTML=cases.map((c,i)=>`<article class="card"><span class="status">${esc(c.status)}</span><h2>${i+1}. ${esc(c.assumption)}</h2><div class="metrics">${c.metrics.map(id=>`<div class="metric"><strong>${F[id].value.toFixed(1)}%</strong><small>${esc(F[id].statement)}<br>${esc(F[id].period)}</small></div>`).join('')}</div><p>${esc(c.text)}</p><p><strong>Next observation:</strong> ${esc(c.next)}</p><details><summary>Inspect supporting and contrary evidence</summary>${c.ids.map(evidence).join('')}</details></article>`).join('');
}).catch(()=>{document.querySelector('#checks').innerHTML='<p>The saved evidence could not be loaded. Serve the examples directory over HTTP and reload, or open the linked full report.</p>';});
