'use strict';
let D,M; const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(x,k=2)=>x===null||x===undefined?'不可用':new Intl.NumberFormat('zh-CN',{minimumFractionDigits:k,maximumFractionDigits:k}).format(x);
const pct=x=>x===null||x===undefined?'不可用':`${x>0?'+':''}${n(x)}%`, usd=x=>x===null?'不可用':`$${n(x,0)}`;
const cls=x=>x<0?'negative':'positive';
const evidence=(text,ref,extra='')=>`<button class="value-button ${extra}" data-ref="${esc(ref)}">${text}</button>`;
const h=(id,num)=>{const s=D.sections.find(x=>x.id===id);return `<div class="section-top"><div><p class="eyebrow">${num} / ${esc(id)}</p><h2>${esc(s.title)}</h2>${s.summary?`<p class="note">${esc(s.summary)}</p>`:''}</div><button data-ref="${id==='returns'||id==='years'?'annual':id==='drawdowns'?'drawdown':id==='entry'?'rolling':id==='cashflow'?'sequence':id==='today'?'concentration':id==='decision'?'policy':'crosscheck'}">来源与计算 ↗</button></div>`};
const factRef=key=>'fact:'+D.facts.find(x=>x.key===key).id;

function drawChart(id,points,series,options={}){
 const width=Math.max(320,Math.min(1000,$(id).clientWidth)),height=300,pad={l:width<500?56:70,r:22,t:18,b:36};
 const values=points.flatMap(p=>series.map(s=>p[s.key]).filter(Number.isFinite));
 if(!values.length){$(id).innerHTML='<p class="note">没有可用观察值。</p>';return;}
 let min=options.min??Math.min(0,...values), max=options.max??Math.max(...values);
 if(max===min){min-=1;max+=1;}if(options.min===undefined&&options.percent)min-=Math.abs(max-min)*.04;if(options.max===undefined)max+=Math.abs(max-min)*.08;
 const x=i=>pad.l+i*(width-pad.l-pad.r)/Math.max(points.length-1,1), y=v=>height-pad.b-(v-min)/(max-min)*(height-pad.t-pad.b);
 let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(options.label||'历史趋势图')}" data-min="${min}" data-max="${max}">`;
 for(let i=0;i<=4;i++){let v=min+(max-min)*i/4;svg+=`<line class="grid" x1="${pad.l}" x2="${width-pad.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${pad.l-9}" y="${y(v)+4}" text-anchor="end">${options.percent?n(v,0)+'%':v>=10000?n(v/10000,1)+'万':n(v,0)}</text>`;}
 if(min<0&&max>=0)svg+=`<line class="zero" x1="${pad.l}" x2="${width-pad.r}" y1="${y(0)}" y2="${y(0)}"/>`;
 for(const i of [...new Set([0,Math.floor((points.length-1)/3),Math.floor((points.length-1)*2/3),points.length-1])])svg+=`<text x="${x(i)}" y="${height-8}" text-anchor="${i===0?'start':i===points.length-1?'end':'middle'}">${esc(String(points[i].date??points[i].step).slice(0,7))}</text>`;
 for(const s of series){let segments=[],segment=[];points.forEach((p,i)=>{if(p[s.key]===null||!Number.isFinite(p[s.key])){if(segment.length)segments.push(segment);segment=[];}else segment.push([x(i),y(p[s.key])]);});if(segment.length)segments.push(segment);
 for(const seg of segments)svg+=`<polyline class="series-line" data-series="${s.key}" points="${seg.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${s.color}" stroke-width="2.4" vector-effect="non-scaling-stroke"/>`;
 points.forEach((p,i)=>{if(!Number.isFinite(p[s.key])||(points.length>600&&i%10!==0&&i!==points.length-1))return;const label=`${p.date??'第'+p.step+'年'}${p.end?' → '+p.end:''} · ${s.name} ${options.percent?pct(p[s.key]):usd(p[s.key])} · ${options.basis||''} · ${(M.refs[options.ref]?.source_ids||[]).join(', ')}`;svg+=`<circle class="chart-point" cx="${x(i)}" cy="${y(p[s.key])}" r="5" fill="transparent" data-index="${i}" data-value="${p[s.key]}" data-series="${s.key}" data-date="${p.date??p.step}" data-label="${esc(label)}" data-ref="${options.ref}" tabindex="-1"><title>${esc(label)}</title></circle>`;});}
 svg+='</svg>';$(id).innerHTML=svg;
 $(id).onpointermove=e=>{const p=e.target.closest('.chart-point');if(p&&options.tip)$(options.tip).textContent=p.dataset.label;};
}

function render(){
 const s=M.summary;
 $('#finrunbook-report').innerHTML=`
 <section id="overview"><p class="eyebrow">研究判断 · 美国大盘股 · 2026-09-04</p><h1>${esc(D.meta.title)}</h1><p class="subtitle">${esc(D.meta.subtitle)}</p><span class="tag">主样本 2006–2025</span><span class="tag">美元 · 未计个人税费</span><span class="tag">历史实绩 / SPY含分红代理</span><p class="view">${esc(D.executive_view.conclusion)}</p><div class="metrics">${D.executive_view.decisive_metrics.map((x,i)=>`<div class="metric ${x.value<0?'negative':''}"><span class="metric-label">${esc(x.label)}</span><button class="metric-value" data-ref="${i<2?'summary':'drawdown'}">${n(x.value)}<span style="font-size:18px">${x.units}</span></button><small>${esc(x.basis)}</small></div>`).join('')}</div><p class="note">本报告默认“大盘”指美股标普500，而非A股。数据按实际端点计算，原始来源、公式和限制可点击查看。</p>
 <details class="detail-row"><summary>如果把“最近20年”算到最新交易日呢？</summary><p>${esc(D.copy.recent_note)}</p><div class="mini-grid"><div class="mini"><span>${M.trailing.start} → ${M.trailing.end}<br>近20年复合年化</span><strong>${evidence(pct(M.trailing.nominal_cagr),'recent')}</strong></div><div class="mini"><span>2026 YTD · 截至9月3日<br>期间回报，非全年</span><strong>${evidence(pct(M.ytd.nominal_return),'recent')}</strong></div><div class="mini"><span>同期实际回报<br>9月CPI尚未公布</span><strong>不可用</strong></div></div></details></section>
 <section id="returns">${h('returns','01')}<div class="wealth-values"><div class="mini"><span>只看价格指数<br>年化 ${n(s.price_cagr)}%</span><strong>${evidence(usd(s.price_wealth),'summary')}</strong></div><div class="mini"><span>SPY含分红代理<br>年化 ${n(s.nominal_cagr)}%</span><strong>${evidence(usd(s.nominal_wealth),'summary')}</strong></div><div class="mini"><span>扣通胀后的购买力<br>年化 ${n(s.real_cagr)}%</span><strong>${evidence(usd(s.real_wealth),'summary')}</strong></div></div><div class="controls"><label>显示口径<select id="wealth-basis"><option value="all">同时比较三种口径</option><option value="nominal">SPY含分红代理</option><option value="real">实际购买力</option><option value="price">标普500价格指数</option></select></label><span class="note">初始本金 $10,000 · 2005年末 → 2025年末</span></div><div class="legend"><span style="--c:#1556a7">含分红代理</span><span style="--c:#08756b">实际购买力</span><span style="--c:#8796a7">仅价格指数</span></div><div id="wealth-chart" class="chart"></div><div id="wealth-tip" class="chart-tip">指向曲线可查看月末数值；点击打开计算依据。</div><div class="callout">${esc(D.copy.arithmetic_note)} 本样本的算术平均为 ${evidence(pct(s.arithmetic_mean),'summary')}，复合年化为 ${evidence(pct(s.nominal_cagr),'summary')}，不能把前者当成长期复利回报。</div><p class="note">2025年10月CPI缺失，实际购买力曲线在该点断开。价格指数与基金代理之间还存在费用、追踪及方法差异，不把整段差额都算作股息贡献。</p></section>
 <section id="years">${h('years','02')}<div class="controls"><label>年度排序<select id="annual-sort"><option value="year">时间顺序</option><option value="worst">最差回报优先</option><option value="best">最佳回报优先</option></select></label><label>比较口径<select id="annual-basis"><option value="nominal">含分红代理</option><option value="real">实际购买力</option><option value="price">仅价格指数</option></select></label><span id="annual-context" class="note"></span></div><div class="table-scroll"><table id="annual-table"><thead><tr><th>自然年</th><th>含分红代理</th><th>价格指数</th><th>实际购买力</th><th>期间</th></tr></thead><tbody></tbody></table></div></section>
 <section id="drawdowns">${h('drawdowns','03')}<div id="drawdown-chart" class="chart"></div><div id="drawdown-tip" class="chart-tip">逐日收盘回撤，峰值为零。不是年度收益。</div><div class="table-scroll"><table id="drawdown-table"><thead><tr><th>峰值 → 谷底</th><th>最大回撤</th><th>首次回本</th><th>峰值至回本</th></tr></thead><tbody>${M.drawdowns.slice(0,5).map(e=>`<tr><td>${e.peak} → ${e.trough}</td><td class="negative">${evidence(pct(e.drawdown),'drawdown')}</td><td>${e.recovery??'样本末未恢复'}</td><td>${n(e.days_underwater/365.2425)} 年</td></tr>`).join('')}</tbody></table></div><div class="callout amber">下跌 ${n(-s.max_drawdown.drawdown)}% 后，需要上涨 ${evidence(pct(s.gain_to_recover),'summary')} 才能回到原点。亏损幅度与回本所需涨幅并不对称。</div><p class="note">${esc(D.copy.extended_note)} ${evidence('查看月度实际回撤依据','drawdown')}</p><details class="detail-row"><summary>补充风险统计：波动率、历史VaR与尾部损失</summary><div class="risk-numbers"><span>年化波动率 <strong>${evidence(n(s.volatility)+'%','summary')}</strong></span><span>1日95%历史VaR <strong>${evidence(n(s.var95)+'%','summary')}</strong></span><span>1日99%历史VaR <strong>${evidence(n(s.var99)+'%','summary')}</strong></span><span>95%尾部平均损失 <strong>${evidence(n(s.es95)+'%','summary')}</strong></span></div><p>这些是2006–2025日回报的样本统计，不代表未来损失概率，VaR更不是最大可能亏损。</p></details></section>
 <section id="entry">${h('entry','04')}<div class="controls"><label>观察样本<select id="rolling-sample"><option value="extended">辅助：1993年以来</option><option value="main">主体：仅2006–2025</option></select></label><label>回报口径<select id="rolling-basis"><option value="nominal">含分红代理</option><option value="real">扣通胀后的实际回报</option></select></label><label>查看某种持有期<select id="rolling-horizon">${[1,3,5,10,15,20].map(v=>`<option value="${v}" ${v===10?'selected':''}>${v} 年</option>`).join('')}</select></label></div><div id="rolling-ranges"></div><p class="note">横条：样本最差至最好年化；竖线：中位数。各持有期共用同一刻度。</p><div class="table-scroll"><table id="rolling-table"><thead><tr><th>持有期</th><th>窗口数</th><th>最差年化</th><th>中位年化</th><th>最好年化</th><th>负收益窗口</th></tr></thead><tbody></tbody></table></div><div id="rolling-answer" class="callout"></div><div id="rolling-chart" class="chart"></div><div id="rolling-tip" class="chart-tip">每一点对应一个买入月末及其完整持有期。</div><p class="note" id="rolling-boundary"></p><p class="note">${esc(D.copy.entry_note)} 样本中的零亏损记录不是保本承诺，15年或20年也不是风险消失的阈值。</p></section>
 <section id="cashflow">${h('cashflow','05')}<div class="controls"><label>每年年初提取初始本金的比例 <strong id="withdraw-label">4%</strong><input id="withdraw-rate" type="range" min="0" max="8" step=".5" value="4"></label><button id="withdraw-reset">重置为4%</button><span class="tag">假设情景 · 非预测</span></div><div id="sequence-values" class="mini-grid"></div><div class="legend"><span style="--c:#1556a7">历史回报顺序</span><span style="--c:#95641d">同一组回报倒序</span></div><div id="sequence-chart" class="chart"></div><div id="sequence-tip" class="chart-tip">横轴是情景步数，不是倒序情景的真实年份。</div><div class="callout">${esc(D.copy.sequence_note)} 把提款比例调为0%，两条曲线终点会重合。</div><p class="note">起始 $100,000，年初固定名义提款，余额不足时只能提取剩余余额；此处未加通胀、税费和额外供款。默认4%只是演示参数，不是建议的安全提取率。</p></section>
 <section id="today">${h('today','06')}<div class="mini-grid"><div class="mini"><span>SPY前十大证券<br>两个Alphabet股类分列</span><strong>${evidence(n(M.concentration.top10)+'%','concentration')}</strong></div><div class="mini"><span>信息技术板块<br>与前十大有重叠</span><strong>${evidence(n(M.concentration.it)+'%',factRef('it_weight'))}</strong></div><div class="mini"><span>FY1预期市盈率<br>依据预测盈利</span><strong>${evidence(n(M.concentration.pe_fy1)+'×',factRef('fy1_pe'))}</strong></div></div><div class="comparison-bar" aria-label="前十大证券权重"><span style="width:${M.concentration.top10}%"></span><span class="remaining" style="width:${100-M.concentration.top10}%"></span></div><p class="note">蓝色：前十大证券；灰色：其余。不是等权的500家公司。</p><div class="callout amber"><span class="tag">简单压力情景</span> 若前十大证券全部下跌30%、其他证券不变，按上述固定权重估算组合下跌 ${evidence(pct(M.concentration.shock30),'concentration')}。这是局部冲击算式，不是完整市场预测；真实相关性和权重会变化。</div><p>我的判断：分散持有大盘股降低了单一公司出问题的影响，但仍暴露于美国股票整体估值、盈利和权重集中。不能因为过去20年年化较高，就认定今天买入的预期回报相同。</p></section>
 <section id="decision">${h('decision','07')}<div class="analysis-grid">${D.copy.decisions.map(x=>`<article class="analysis-card"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></section>
 <section id="method">${h('method','08')}<p class="note">数据校验检验记录、引用与计算，不等于独立审计。数字和语义由同一agent复核，另执行确定性的重算与浏览器检查。</p>${D.methodology.map((x,i)=>`<details class="detail-row" ${i===0?'open':''}><summary>${esc(x.term)}</summary><p>${esc(x.text)}</p>${(x.calculation_ids||[]).map(id=>evidence(id,'calc:'+id)).join(' · ')} ${(x.source_ids||[]).map(id=>`<a href="${esc(D.sources.find(s=>s.id===id).url)}" target="_blank" rel="noopener noreferrer">${id}</a>`).join(' · ')}</details>`).join('')}<p class="note">发行人核对：Yahoo 9月3日SPY收盘 ${usd(M.crosscheck.latest_yahoo_close)}（精确至美分为 $${n(M.crosscheck.latest_yahoo_close)}）；7月YTD代理 ${pct(M.crosscheck.yahoo_july_ytd)}，发行人Market Value ${pct(M.crosscheck.ssga_midpoint_ytd)}。差异约 ${n(M.crosscheck.midpoint_gap_pp)} 个百分点，未强行消除。</p></section>`;
 $('#wealth-basis').onchange=wealthChart;$('#annual-sort').onchange=annualTable;$('#annual-basis').onchange=annualTable;
 ['#rolling-sample','#rolling-basis','#rolling-horizon'].forEach(id=>$(id).onchange=rollingView);
 $('#withdraw-rate').oninput=sequenceView;$('#withdraw-reset').onclick=()=>{$('#withdraw-rate').value='4';sequenceView();};
 wealthChart();annualTable();rollingView();sequenceView();drawChart('#drawdown-chart',M.drawdown_daily,[{key:'drawdown',name:'峰值回撤',color:'#b33a39'}],{percent:true,max:0,ref:'drawdown',tip:'#drawdown-tip',basis:'SPY含分红代理 · 日收盘'});
 $('#validation-state').textContent=`账本校验：${D.validation.status} · ${D.validation.warnings??(D.validation.issues||[]).filter(x=>x.severity==='warning').length} 项已披露警告（Yahoo为二级数据源，调整方法需要审阅）`;
}
function wealthChart(){const basis=$('#wealth-basis').value;let series=[{key:'price',name:'价格指数',color:'#8796a7'},{key:'nominal',name:'含分红代理',color:'#1556a7'},{key:'real',name:'实际购买力',color:'#08756b'}];if(basis!=='all')series=series.filter(s=>s.key===basis);drawChart('#wealth-chart',M.wealth,series,{ref:'annual',tip:'#wealth-tip',basis:'初始1万美元 · 月末 · 未计个人税费'});}
function annualTable(){let a=[...M.annual],basis=$('#annual-basis').value,sort=$('#annual-sort').value;if(sort!=='year')a.sort((x,y)=>sort==='worst'?x[basis]-y[basis]:y[basis]-x[basis]);$('#annual-table tbody').innerHTML=a.map(x=>`<tr data-year="${x.year}"><td>${x.year}</td>${['nominal','price','real'].map(k=>`<td class="${cls(x[k])}" ${k===basis?'style="background:#eef4fb"':''}>${evidence(pct(x[k]),'annual')}</td>`).join('')}<td class="note">${x.start} → ${x.end}</td></tr>`).join('');const bad=M.annual.filter(x=>x[basis]<0).length;$('#annual-context').textContent=`所选口径：20个年度中${bad}个年度为负；不代表未来亏损概率。`;}
function rollingView(){let sample=$('#rolling-sample').value,basis=$('#rolling-basis').value,horizon=$('#rolling-horizon').value,rows=M.rolling[sample];const stats=Object.entries(rows).map(([h,x])=>({h,...x.stats[basis]}));const lo=Math.min(0,...stats.map(s=>s.min)),hi=Math.max(...stats.map(s=>s.max)),pos=v=>(v-lo)/(hi-lo)*100;
 $('#rolling-ranges').innerHTML=stats.map(s=>`<div class="range-row"><span>${s.h}年</span><div class="range-track"><span class="range-fill" style="left:${pos(s.min)}%;width:${pos(s.max)-pos(s.min)}%"></span><span class="range-median" style="left:${pos(s.median)}%"></span></div><span>${pct(s.min)} 至 ${pct(s.max)}</span></div>`).join('');
 $('#rolling-table tbody').innerHTML=stats.map(s=>`<tr data-horizon="${s.h}"><td>${s.h}年</td><td>${s.count}</td><td class="${cls(s.min)}">${evidence(pct(s.min),'rolling')}</td><td>${pct(s.median)}</td><td>${pct(s.max)}</td><td>${s.negative}/${s.count}（${n(s.negative_pct,1)}%）</td></tr>`).join('');
 const t=rows[horizon].stats[basis];$('#rolling-answer').innerHTML=`${sample==='extended'?'辅助长样本':'主体20年样本'}中，持有${horizon}年的最差年化为 <strong class="${cls(t.min)}">${pct(t.min)}</strong>，对应 ${t.worst.start} → ${t.worst.end}；${t.negative}个窗口最终亏损。${t.count===1?'这里只有一个完整窗口，不能用来推断胜率。':''}`;
 $('#rolling-boundary').textContent=sample==='extended'?`辅助样本：1993年2月至2026年8月末。${basis==='real'?'实际口径仅使用CPI可用端点，最晚到2026年7月；缺失端点排除，不补值。':'月末入场、按完整月数计算年化。'}`:'主体窗口：2005年12月末至2025年12月末；只容纳一个完整20年持有期。';
 drawChart('#rolling-chart',rows[horizon].observations.map(o=>({date:o.start,value:o[basis],end:o.end})),[{key:'value',name:`${horizon}年${basis==='real'?'实际':'名义'}年化`,color:'#1556a7'}],{percent:true,ref:'rolling',tip:'#rolling-tip',basis:'横轴=买入月末；每点完整持有'+horizon+'年'});
}
function simulate(returns,rate){let balance=100000,withdrawn=0,points=[{step:0,balance}];returns.forEach((r,i)=>{let cash=Math.min(balance,100000*rate/100);balance=(balance-cash)*(1+r/100);withdrawn+=cash;points.push({step:i+1,balance});});return{balance,withdrawn,points};}
function sequenceView(){const rate=Number($('#withdraw-rate').value),returns=M.annual.map(x=>x.nominal),a=simulate(returns,rate),b=simulate([...returns].reverse(),rate);$('#withdraw-label').textContent=n(rate,1)+'%';$('#sequence-values').innerHTML=`<div class="mini"><span>历史顺序 · 期末余额</span><strong>${evidence(usd(a.balance),'sequence')}</strong></div><div class="mini"><span>倒序情景 · 期末余额</span><strong>${evidence(usd(b.balance),'sequence')}</strong></div><div class="mini"><span>累计提款 · 历史 / 倒序</span><strong style="font-size:18px">${usd(a.withdrawn)} / ${usd(b.withdrawn)}</strong></div>`;drawChart('#sequence-chart',a.points.map((p,i)=>({step:p.step,historical:p.balance,reversed:b.points[i].balance})),[{key:'historical',name:'历史回报顺序',color:'#1556a7'},{key:'reversed',name:'相同回报倒序',color:'#95641d'}],{ref:'sequence',tip:'#sequence-tip',basis:'假设情景 · 年初固定提款'});window.finrunbookScenario={rate,historical:a,reversed:b};}

function showEvidence(ref){let ids=[],fids=[],sids=[];
 if(ref==='policy'){fids=D.facts.filter(x=>['horizon','allocation','index_risk'].includes(x.key)).map(x=>x.id);}
 else if(ref.startsWith('fact:'))fids=[ref.slice(5)];else if(ref.startsWith('calc:'))ids=[ref.slice(5)];else{const r=M.refs[ref];if(!r)return;ids=r.calculation_ids||[];fids=r.fact_ids||[];sids=r.source_ids||[];}
 const calculations=D.calculations.filter(c=>ids.includes(c.id));fids=[...new Set([...fids,...calculations.flatMap(c=>c.input_fact_ids)])];const facts=D.facts.filter(f=>fids.includes(f.id));sids=[...new Set([...sids,...facts.flatMap(f=>f.source_ids)])];
 $('#dialog-title').textContent='证据、口径与计算';$('#evidence-body').innerHTML=calculations.map(c=>`<div class="evidence-item"><h3>${esc(c.description)}</h3><span class="badge">${c.id}</span><p class="note">${esc(c.period)} · ${esc(c.units)}</p><strong>公式</strong><pre>${esc(c.expression)}</pre><p>输入：${c.input_fact_ids.map(id=>evidence(id,'fact:'+id)).join(' · ')}</p><details><summary>计算结果（完整值见报告JSON）</summary><pre>${esc(JSON.stringify(c.result,null,2).slice(0,7000))}</pre></details></div>`).join('')+facts.map(f=>`<div class="evidence-item"><h3>${f.id}</h3><p>${esc(f.statement)}</p><span class="badge">${f.status==='provider-reported'?'供应商观察':f.status==='company-reported'?'发行人披露':f.status==='calculated'?'计算结果':esc(f.status)}</span>${f.value!==undefined?`<pre>${esc(JSON.stringify(f.value,null,2))} ${esc(f.units||'')}</pre>`:''}${D.evidence.filter(e=>f.evidence_ids.includes(e.id)).map(e=>`<p class="note"><strong>${e.id}</strong> · ${esc(e.locator)}<br>${esc(e.content)}</p>`).join('')}</div>`).join('')+`<h3 style="margin-top:18px">原始来源</h3>`+D.sources.filter(s=>sids.includes(s.id)).map(sourceCard).join('');
 if(!$('#evidence-dialog').open)$('#evidence-dialog').showModal();$('#evidence-dialog').scrollTop=0;
}
function sourceCard(s){return `<article class="source-item"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><span class="badge">${s.id} · ${s.primary?'官方/一手':'二级行情'}</span><p class="note">${esc(s.publisher)} · 读取 ${esc(s.retrieved_at?.slice(0,10))}<br>${esc(s.license_or_terms)}</p></article>`;}
function sourceDrawer(){$('#dialog-title').textContent=`来源目录 · ${D.sources.length}项`;$('#evidence-body').innerHTML='<input class="source-search" id="source-search" placeholder="搜索机构、标题或来源ID" aria-label="搜索来源"><div id="source-list"></div>';const update=()=>{let q=$('#source-search').value.toLowerCase();$('#source-list').innerHTML=D.sources.filter(s=>JSON.stringify([s.id,s.title,s.publisher]).toLowerCase().includes(q)).map(sourceCard).join('');};$('#source-search').oninput=update;update();$('#evidence-dialog').showModal();$('#source-search').focus();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ref]');if(b)showEvidence(b.dataset.ref);});$('#dialog-close').onclick=()=>$('#evidence-dialog').close();$('#sources-open').onclick=()=>D&&sourceDrawer();
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!D)return;wealthChart();rollingView();sequenceView();drawChart('#drawdown-chart',M.drawdown_daily,[{key:'drawdown',name:'峰值回撤',color:'#b33a39'}],{percent:true,max:0,ref:'drawdown',tip:'#drawdown-tip',basis:'SPY含分红代理 · 日收盘'});},80);});
fetch('report-data.json').then(r=>{if(!r.ok)throw new Error('报告数据无法载入');return r.json();}).then(data=>{D=data;M=D.model;window.finrunbookReportData=D;render();}).catch(e=>{$('#finrunbook-report').innerHTML=`<p role="alert">${esc(e.message)}。请通过本地HTTP服务器访问此报告。</p>`;});
